# Build with  'podman build . -f containerfile -t a2a_mqtt_gateway_bridge'
# Run with 'podman run -p 10004:10004
FROM dart:3.9.2
WORKDIR /app
COPY . .
RUN dart pub get
RUN dart compile exe src/mqtt_gateway_bridge.dart
EXPOSE 10005
ENTRYPOINT ["/app/src/mqtt_gateway.exe"]