name: movie_agent
description: An implementation of the Google A2A Movie Agent sample
version: 1.0.1
repository: https://github.com/shamblett/a2a-dart-samples/MovieAgent
publish_to: none
funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
    colorize: '^3.0.0'
    a2a: '^3.0.0'
    dartantic_ai: '^1.0.7'
    dartantic_interface: '^1.0.2'
    json_schema: '^5.2.1'
    oxy: '^0.0.3'
    uuid: '^4.5.1'

dev_dependencies:
  lints: '^6.0.0'