# Build with  'podman build . -f containerfile -t a2a-coder-agent'
# Run with 'podman run -p 41241:41241 -e GEMINI_API_KEY='<key>' a2a-coder-agent'
FROM dart:3.9.2
WORKDIR /app
COPY . .
RUN dart pub get
RUN dart compile exe coder_agent.dart
EXPOSE 41241
ENTRYPOINT ["/app/coder_agent.exe"]