name: coder
description: An implementation of the Google A2A Coder sample
version: 1.0.0
repository: https://github.com/shamblett/a2a-dart-samples/Coder
publish_to: none
funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
    colorize: '^3.0.0'
    a2a: '^2.3.3'
    dartantic_ai: '^1.0.7'
    dartantic_interface: '^1.0.2'
    json_schema: '^5.2.1'
    oxy: '^0.0.3'

dev_dependencies:
  lints: '^6.0.0'
  dart_code_metrics_presets: '^2.25.0'