# Build with  'podman build . -f containerfile -t a2a-content-editor-agent'
# Run with 'podman run -p 10003:10003 -e GEMINI_API_KEY='<key>'
FROM dart:3.9.2
WORKDIR /app
COPY . .
RUN dart pub get
RUN dart compile exe content_editor.dart
EXPOSE 10003
ENTRYPOINT ["/app/content_editor.exe"]