name: content_editor
description: An implementation of the Google A2A Content Editor sample
version: 1.0.1
repository: https://github.com/shamblett/a2a-dart-samples/ContentEditor
publish_to: none
funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
    colorize: '^3.0.0'
    a2a: '^3.0.0'
    dartantic_ai: '^1.0.7'
    dartantic_interface: '^1.0.2'

dev_dependencies:
  lints: '^6.0.0'